---
name: "Deploy"
on:
  workflow_call:
    inputs:
      base_path:
        description: 'Specifies the path of the root terraform module.'
        required: true
        type: string
      infra_type:
        description: 'Specifies the type of deployment. Used for plan title.'
        required: true
        type: string
      provider:
        description: 'Specifies the cloud provider for auth.'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  check-tag:
    if: |
      startsWith(github.ref, 'refs/tags') &&
      (github.event_name == 'push' ||
      github.event_name == 'release')
    runs-on: ubuntu-latest
    outputs:
      has_tag: ${{ steps.check-tag.outputs.has_tag }}
    steps:
      - name: Check tag
        id: check-tag
        run: |
          has_tag=$([[ ${{ github.ref }} =~ ^refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo 'true' || echo 'false')
          echo "has_tag = $has_tag"
          echo "has_tag=$has_tag" >> $GITHUB_OUTPUT
  # build-title:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     plan-title: ${{ steps.check-tag.outputs.has_tag }}
  #   steps:
  #     - name: Build Plan Title
  #       id: plan-title
  #       run: |
  #         plan_title="AWS ${{ inputs.gh_environment }} Deploy Plan"
  #         echo "plan_title=$has_tag" >> $GITHUB_OUTPUT

  plan-dev:
    uses: ./.github/workflows/plan.yml
    # uses: shortpoet/tf-web/.github/workflows/plan.yml@main
    # uses: shortpoet/.github/workflows/plan.yml@main
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    secrets: inherit
    with:
      provider: ${{ inputs.provider }}
      gh_environment: 'dev'
      path: ${{ inputs.base_path }}/envs/dev
      plan-title: "AWS ${{ inputs.gh_environment }} ${{ inputs.infra_type }} plan"

  apply-dev:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    uses: ./.github/workflows/apply.yml
    secrets: inherit
    needs: [plan-dev]
    with:
      provider: ${{ inputs.provider }}
      gh_environment: 'dev'
      path: ${{ inputs.base_path }}/envs/dev
      infra_type: ${{ inputs.infra_type }}

  plan-uat:
    if: |
      (startsWith(github.ref, 'refs/pull') &&
      endsWith(github.ref, '/merge') &&
      github.head_ref == 'uat' &&
      github.base_ref == 'main' &&
      github.event_name == 'pull_request')
    uses: ./.github/workflows/plan.yml
    secrets: inherit
    with:
      provider: ${{ inputs.provider }}
      gh_environment: 'uat'
      path: ${{ inputs.base_path }}/envs/uat
      plan-title: "AWS ${{ inputs.gh_environment }} ${{ inputs.infra_type }} plan"

  apply-uat:
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push'
    uses: ./.github/workflows/apply.yml
    secrets: inherit
    # needs: [plan-uat, apply-dev]
    with:
      provider: ${{ inputs.provider }}
      gh_environment: 'uat'
      path: ${{ inputs.base_path }}/envs/uat
      infra_type: ${{ inputs.infra_type }}

  plan-prod:
    if: |
      (needs.check-tag.outputs.has_tag == 'true' &&
      github.event_name == 'release')
    uses: ./.github/workflows/plan.yml
    secrets: inherit
    needs : [check-tag]
    # needs : [apply-uat, check-tag]
    with:
      provider: ${{ inputs.provider }}
      gh_environment: 'prod'
      path: ${{ inputs.base_path }}/envs/prod
      plan-title: "AWS ${{ inputs.gh_environment }} ${{ inputs.infra_type }} plan"

  apply-prod:
    if: |
      needs.check-tag.outputs.has_tag == 'true' &&
      github.event_name == 'release'
    uses: ./.github/workflows/apply.yml
    secrets: inherit
    # needs : [check-tag]
    needs : [plan-prod, check-tag]
    with:
      provider: ${{ inputs.provider }}
      gh_environment: 'prod'
      path: ${{ inputs.base_path }}/envs/prod
      infra_type: ${{ inputs.infra_type }}
