---
name: Base Infra

env:
  APP_DIR: workers
  IAC_DIR: .iac/infra_base
  BUILD_DIR: dist
  BUILD_ARTIFACT: dist
  TF_VAR_build_cicd: true

on:
  pull_request:
    branches:
      - main
      - uat
      - develop
    paths:
      - '.iac/infra_base/**'
      - '.github/workflows/infra-base.yml'
      - 'workers/**'
  push:
    branches:
      - main
      - uat
      - develop
    paths:
      - '.iac/infra_base/**'
      - '.github/workflows/infra-base.yml'
      - 'workers/**'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10 #
  release:
    types:
      - published
    paths:
      - '.iac/infra_base/**'
      - '.github/workflows/infra-base.yml'
      - 'workers/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  paths-filter:
    if:
      (
        (startsWith(github.ref, 'refs/pull') &&
        endsWith(github.ref, '/merge') &&
        github.head_ref == 'uat' &&
        github.base_ref == 'main' &&
        github.event_name == 'pull_request')
      ) ||
      (github.event_name == 'push' &&
        (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')
      ) ||
      github.event_name == 'release'
    outputs:
      infra_base: ${{ steps.filter.outputs.infra_base }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            infra_base:
              - '.iac/infra_base/aws/**'
              - '.github/workflows/infra-base.yml'
              - 'workers/**'

  build-node:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: |
      needs.paths-filter.outputs.infra_base == 'true' ||
      github.event_name == 'release'
    outputs:
      build-artifact-uuid: ${{ steps.build-artifact-uuid.outputs.BUILD_ARTIFACT_UUID }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        env:
          NODE_ENV: development
        working-directory: ${{ env.APP_DIR }}
        run: |
          npm install --global vite pnpm wrangler
          pnpm i

      - name: Build
        working-directory: ${{ env.APP_DIR }}
        env:
          NODE_ENV: production
        run: |
          pnpm run build-ci

      - name: Compress build
        working-directory: ${{ env.APP_DIR }}
        run: |
          cd ${{ env.BUILD_DIR }}
          zip -r ${{ env.BUILD_ARTIFACT }}.zip ./*

      - name: Set build artifact UUID
        id: build-artifact-uuid
        env:
          BUILD_ARTIFACT_UUID: build-${{ github.sha }}-${{ github.ref_name }}
          BUILD_ARTIFACT_UUID_UAT: build-${{ github.sha }}-${{ github.head_ref }}
          IS_DEV: ${{ github.ref == 'refs/heads/develop' }}
          IS_MAIN: ${{ github.ref == 'refs/heads/main' }}
          IS_UAT: ${{ github.head_ref == 'uat' }} && ${{ github.base_ref == 'main' }} && ${{ github.event_name == 'pull_request' }} && ${{ startsWith(github.ref, 'refs/pull') }} && ${{ endsWith(github.ref, '/merge') }}
          IS_RELEASE: ${{ github.event_name == 'release' }} && ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          if [ "$IS_DEV" = true ]; then
            echo "BUILD_ARTIFACT_UUID=${BUILD_ARTIFACT_UUID}" >> $GITHUB_OUTPUT
          elif [ "$IS_MAIN" = true ]; then
            echo "BUILD_ARTIFACT_UUID=${BUILD_ARTIFACT_UUID}" >> $GITHUB_OUTPUT
          elif [ "$IS_RELEASE" = 'true && true' ]; then
            echo "BUILD_ARTIFACT_UUID=${BUILD_ARTIFACT_UUID}" >> $GITHUB_OUTPUT
          elif [ "$IS_UAT" = 'true && true && true && true && true' ]; then
            echo "BUILD_ARTIFACT_UUID=${BUILD_ARTIFACT_UUID_UAT}" >> $GITHUB_OUTPUT
          fi

      - name: Upload build
        id: upload-build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build-artifact-uuid.outputs.BUILD_ARTIFACT_UUID }}
          path: "${{ env.APP_DIR }}/${{ env.BUILD_DIR }}/${{ env.BUILD_ARTIFACT }}.zip"

  deploy:
    uses: shortpoet/.github/.github/workflows/deploy-dev_push-uat_merge-prod_release.yml@main
    secrets: inherit
    # needs: [paths-filter]
    needs: [paths-filter, build-node]
    # can't seem to use if release here because of needs
    if: |
      needs.paths-filter.outputs.infra_base == 'true' ||
      github.event_name == 'release'
    with:
      base_path: .iac/infra_base/aws
      infra_type: Base
      provider: aws
      # build_path: "workers/dist"
      # build_artifact: "dist"
      # build_artifact_uuid: ${{ needs.build-node.outputs.build-artifact-uuid }}
